### ISSUE TITLE
Wrong IN-8 footprint

### ISSUE THREAD

**Issue by micmys** [judge2005/Eagle-Nixie-Libs#3]
The footprint for  IN-8 Nixie is almost certainly wrong. The pins should be placed on a ring with radius 4.75 mm and spaced 30 degrees apart, with one spot unused. However, in the footprint distance seems to be lower than 30 degrees.

**Comment by judge2005** [comment]
I think you are correct. This is a footprint that was carried over from the source library.

**Comment by judge2005** [comment]
Fixed
