### ISSUE TITLE
Mirrored IN-14 Footprint

### ISSUE THREAD

**Issue by famicomical** [judge2005/Eagle-Nixie-Libs#5]
The KiCAD footprint for IN-14 is mirrored and matches the pin order for a bottom-view. KiCAD footprints display the component pinout as it is mounted on the top layer, so the pin order should match a top view of the tube. Attached are the IN-14 pinout and a screenshot of the current footprint. They match, but they shouldn't.
![in-14 diagram](https://user-images.githubusercontent.com/15517050/141539337-60547800-a644-4fa7-aaa9-57ecaad714c1.PNG)
![incorrectfp](https://user-images.githubusercontent.com/15517050/141539434-0d0eb0a2-5814-4376-9a31-34aa0e38c836.PNG)

**Comment by judge2005** [comment]
Fixed
