### ISSUE TITLE
IN-14 Missmatch Pin Name, Pin Number

### ISSUE THREAD

**Issue by twalter23** [judge2005/Eagle-Nixie-Libs#6]
Altough IN-14 footprint seems to be ok : 

![image](https://user-images.githubusercontent.com/114344089/213921363-b7c2668b-240c-4b6e-ab1d-c06047816c72.png)

IN-14 pin name and pin number do not match :

![image](https://user-images.githubusercontent.com/114344089/213921328-5216849d-8a78-4b00-b160-66f519ae133c.png)

**Comment by judge2005** [comment]
Ugh. Fixed.
